// <auto-generated />
using System;
using Maliev.ChatbotService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.ChatbotService.Infrastructure.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20260102174942_AddFallbackResponseTemplatesAndFixPendingChanges")]
    partial class AddFallbackResponseTemplatesAndFixPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SummaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "Channel", "Status");

                    b.ToTable("ConversationSessions");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StructuredSummary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("ConversationSummaries");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.FallbackResponseTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludesContactInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("ScenarioType", "Language", "IsActive");

                    b.ToTable("FallbackResponseTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncludesContactInfo = false,
                            IsActive = true,
                            Language = 1,
                            Priority = 100,
                            ResponseText = "I apologize, but I encountered an unexpected error while processing your request. Please try again in a few moments. If the issue persists, you can contact our support team at support@maliev.com.",
                            ScenarioType = "UnexpectedError"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncludesContactInfo = false,
                            IsActive = true,
                            Language = 2,
                            Priority = 100,
                            ResponseText = "ขออภัยด้วยครับ เกิดข้อผิดพลาดที่ไม่คาดคิดขณะประมวลผลคำขอของคุณ โปรดลองอีกครั้งในอีกสักครู่ หากปัญหายังคงอยู่ คุณสามารถติดต่อทีมสนับสนุนของเราได้ที่ support@maliev.com",
                            ScenarioType = "UnexpectedError"
                        });
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.IdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalPlatformId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LinkCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlatformName")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("WebhookConfirmationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlatformId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("PlatformName", "ExternalPlatformId")
                        .IsUnique();

                    b.ToTable("IdentityLinks");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationParameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "ExecutedAt");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SearchDomainLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAt");

                    b.HasIndex("Domain");

                    b.HasIndex("SessionId");

                    b.ToTable("SearchDomainLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SystemInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessConstraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnableWebSearch")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LogSearchDomains")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonaDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionTemplates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name", "Version");

                    b.ToTable("SystemInstructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowedTopics = "manufacturing,materials,processes,orders,quotations,technical specifications,quality standards,production capabilities,lead times,CNC machining,welding,casting,forging,sheet metal fabrication,metals,plastics,composites,ISO standards,ASTM standards,DIN standards",
                            BusinessConstraints = "STRICT RULES - YOU MUST FOLLOW THESE:\r\n\r\n1. ONLY discuss topics related to manufacturing, materials, processes, orders, and Maliev company services\r\n2. REJECT politely any questions about:\r\n   - Weather, sports, entertainment, politics\r\n   - Personal advice\r\n   - Competitor services or pricing\r\n   - Non-manufacturing topics\r\n\r\n3. When rejecting off-topic questions, ALWAYS redirect to manufacturing topics like:\r\n   \"I'm specialized in manufacturing assistance. I can help you with:\r\n   - Material selection and specifications\r\n   - Manufacturing process recommendations\r\n   - Order status and quotations\r\n   - Technical drawings and requirements\r\n   What would you like to know about our manufacturing services?\"\r\n\r\n4. For internal agents with CRM access:\r\n   - Provide quotation and order status details\r\n   - Offer quick action buttons (Send Reminder, Update Status, etc.)\r\n   - Access customer history\r\n\r\n5. NEVER:\r\n   - Share confidential company information\r\n   - Make commitments without proper authorization\r\n   - Provide competitor pricing or comparison",
                            EnableWebSearch = false,
                            IsActive = true,
                            LogSearchDomains = true,
                            Name = "Manufacturing Chatbot - Default",
                            PersonaDefinition = "You are a helpful AI assistant for Maliev Manufacturing Company. You specialize in manufacturing processes, materials, and customer inquiries about our services.\r\n\r\nYour expertise includes:\r\n- Manufacturing processes (CNC machining, welding, casting, forging, sheet metal fabrication)\r\n- Materials (metals, plastics, composites)\r\n- Quality standards (ISO, ASTM, DIN)\r\n- Production capabilities and lead times\r\n- Technical specifications and drawings\r\n- Order status and quotation information\r\n\r\nCommunication style:\r\n- Professional and courteous\r\n- Clear and concise\r\n- Technical when needed, but accessible to non-experts\r\n- Proactive in offering relevant information\r\n- Patient with follow-up questions",
                            RejectionTemplates = "{\r\n  \"weather\": \"I'm specialized in manufacturing assistance and don't have information about weather. However, I can help you with material selection, manufacturing processes, or order status. What would you like to know about our manufacturing services?\",\r\n  \"competitor\": \"I focus on helping you with Maliev's manufacturing services and capabilities. I'd be happy to discuss our offerings, pricing, or how we can meet your manufacturing needs. What specific requirements do you have?\",\r\n  \"general\": \"I'm here to assist with manufacturing-related questions. I can help you with:\\n- Material selection and specifications\\n- Manufacturing process recommendations\\n- Order status and quotations\\n- Technical drawings and requirements\\nWhat would you like to know about our manufacturing services?\"\r\n}",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "Key");

                    b.ToTable("UserMemories");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstagramId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InternalUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacebookId")
                        .IsUnique()
                        .HasFilter("[FacebookId] IS NOT NULL");

                    b.HasIndex("InstagramId")
                        .IsUnique()
                        .HasFilter("[InstagramId] IS NOT NULL");

                    b.HasIndex("InternalUserId")
                        .HasFilter("[InternalUserId] IS NOT NULL");

                    b.HasIndex("LineUserId")
                        .IsUnique()
                        .HasFilter("[LineUserId] IS NOT NULL");

                    b.HasIndex("WhatsAppId")
                        .IsUnique()
                        .HasFilter("[WhatsAppId] IS NOT NULL");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Sessions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummary", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithOne("Summary")
                        .HasForeignKey("Maliev.ChatbotService.Domain.Entities.ConversationSummary", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.IdentityLink", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.OperationLog", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.Message", "Message")
                        .WithMany("OperationLogs")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("OperationLogs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SearchDomainLog", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserMemory", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.Message", "SourceMessage")
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Memories")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMessage");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.Navigation("OperationLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("IdentityLinks");

                    b.Navigation("Memories");

                    b.Navigation("OperationLogs");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
