// <auto-generated />
using System;
using Maliev.ChatbotService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.ChatbotService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20260701033116_AddConversationSummaryBatchJobs")]
    partial class AddConversationSummaryBatchJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SummaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "Channel", "Status");

                    b.ToTable("ConversationSessions");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StructuredSummary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("ConversationSummaries");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummaryBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StructuredSummary")
                        .HasColumnType("jsonb");

                    b.Property<string>("TokenUsageJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchJobId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ConversationSummaryBatchItems");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummaryBatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("ConversationSummaryBatchJobs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.FallbackResponseTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludesContactInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("ScenarioType", "Language", "IsActive");

                    b.ToTable("FallbackResponseTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncludesContactInfo = false,
                            IsActive = true,
                            Language = 1,
                            Priority = 100,
                            ResponseText = "I'm Mali, and I apologize, but I encountered an unexpected error while processing your request. Please try again in a few moments. If the issue persists, you can contact our support team at support@maliev.com.",
                            ScenarioType = "UnexpectedError"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncludesContactInfo = false,
                            IsActive = true,
                            Language = 2,
                            Priority = 100,
                            ResponseText = "มะลิขออภัยด้วยนะคะ เกิดข้อผิดพลาดที่ไม่คาดคิดขณะประมวลผลคำขอของคุณ โปรดลองอีกครั้งในอีกสักครู่ หากปัญหายังคงอยู่ คุณสามารถติดต่อทีมสนับสนุนของเราได้ที่ support@maliev.com ค่ะ",
                            ScenarioType = "UnexpectedError"
                        });
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.IdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalPlatformId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LinkCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlatformName")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("WebhookConfirmationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlatformId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("PlatformName", "ExternalPlatformId")
                        .IsUnique();

                    b.ToTable("IdentityLinks");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TopicKey");

                    b.HasIndex("TopicKey", "FactKey")
                        .IsUnique();

                    b.ToTable("KnowledgeBase");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationParameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "ExecutedAt");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SearchDomainLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAt");

                    b.HasIndex("Domain");

                    b.HasIndex("SessionId");

                    b.ToTable("SearchDomainLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SystemInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessConstraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableWebSearch")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LogSearchDomains")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonaDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RejectionTemplates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TopicKey");

                    b.HasIndex("Name", "Version");

                    b.ToTable("SystemInstructions");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "Key");

                    b.ToTable("UserMemories");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstagramId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InternalUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacebookId")
                        .IsUnique()
                        .HasFilter("\"FacebookId\" IS NOT NULL");

                    b.HasIndex("InstagramId")
                        .IsUnique()
                        .HasFilter("\"InstagramId\" IS NOT NULL");

                    b.HasIndex("InternalUserId")
                        .HasFilter("\"InternalUserId\" IS NOT NULL");

                    b.HasIndex("LineUserId")
                        .IsUnique()
                        .HasFilter("\"LineUserId\" IS NOT NULL");

                    b.HasIndex("WhatsAppId")
                        .IsUnique()
                        .HasFilter("\"WhatsAppId\" IS NOT NULL");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Sessions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummary", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithOne("Summary")
                        .HasForeignKey("Maliev.ChatbotService.Domain.Entities.ConversationSummary", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummaryBatchItem", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSummaryBatchJob", "BatchJob")
                        .WithMany("Items")
                        .HasForeignKey("BatchJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchJob");

                    b.Navigation("Session");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.IdentityLink", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.OperationLog", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.Message", "Message")
                        .WithMany("OperationLogs")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("OperationLogs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.SearchDomainLog", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserMemory", b =>
                {
                    b.HasOne("Maliev.ChatbotService.Domain.Entities.Message", "SourceMessage")
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maliev.ChatbotService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Memories")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMessage");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.ConversationSummaryBatchJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.Message", b =>
                {
                    b.Navigation("OperationLogs");
                });

            modelBuilder.Entity("Maliev.ChatbotService.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("IdentityLinks");

                    b.Navigation("Memories");

                    b.Navigation("OperationLogs");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
